#!/bin/bash

t0001-help () {
	cat <<-EOF
	Topoloy commands:
	    set-up
	    tear-down
	    show
	EOF

}

t0001-show () {
	cat <<-EOF
	t0001:
	    h1 (10.168.0.1)
	     | (10.168.1.1)
	     |
	     | (10.168.1.2)
	    h2 (10.168.0.2)
	EOF
}

t0001-set-up () {
	sudo mkdir -p /etc/netns/t0001-{h1,h2}
	echo h1 | sudo tee /etc/netns/t0001-h1/hostname >/dev/null
	echo h2 | sudo tee /etc/netns/t0001-h2/hostname >/dev/null
	sudo tee /etc/netns/t0001-h1/hosts >/dev/null <<-EOF
		127.0.0.1	localhost
		10.168.0.1	h1
		10.168.0.2	h2

		# The following lines are desirable for IPv6 capable hosts
		::1     ip6-localhost	ip6-loopback localhost
		fe00::0 ip6-localnet
		ff00::0 ip6-mcastprefix
		ff02::1 ip6-allnodes
		ff02::2 ip6-allrouters
	EOF
	sudo cp /etc/netns/t0001-h1/hosts /etc/netns/t0001-h2/hosts
	sudo ip netns add t0001-h1
	sudo ip netns add t0001-h2
	sudo ip link add type veth
	sudo ip link set dev veth0 netns t0001-h1 name eth0
	sudo ip link set dev veth1 netns t0001-h2 name eth0
	sudo ip netns exec t0001-h1 ip link add name h1 type dummy
	sudo ip netns exec t0001-h1 ip addr add 10.168.0.1/32 dev h1
	sudo ip netns exec t0001-h2 ip link add name h2 type dummy
	sudo ip netns exec t0001-h2 ip addr add 10.168.0.2/32 dev h2
	sudo ip netns exec t0001-h1 ip addr add 10.168.1.1/30 \
		broadcast 10.168.1.3 dev eth0
	sudo ip netns exec t0001-h2 ip addr add 10.168.1.2/30 \
		broadcast 10.168.1.3 dev eth0
	sudo ip netns exec t0001-h1 ip link set h1 up
	sudo ip netns exec t0001-h2 ip link set h2 up
	sudo ip netns exec t0001-h1 ip link set eth0 up
	sudo ip netns exec t0001-h2 ip link set eth0 up
	sudo ip netns exec t0001-h1 ip route add 10.168.0.2/32 via 10.168.1.2
	sudo ip netns exec t0001-h2 ip route add 10.168.0.1/32 via 10.168.1.1
}

t0001-tear-down () {
	if [[ ! -d /etc/netns/t0001-h1 || ! -d /etc/netns/t0001-h2 ]] ; then
		echo 'Error: no namespaces, did you "ns t0001 start"?' >/dev/stderr
		exit 1
	fi
	sudo ip netns exec t0001-h1 ip link set eth0 down
	sudo ip netns exec t0001-h2 ip link set eth0 down
	sudo ip netns exec t0001-h1 ip link delete eth0
	sudo ip netns exec t0001-h1 ip link delete h1
	sudo ip netns exec t0001-h2 ip link delete h2
	sudo ip netns delete t0001-h1
	sudo ip netns delete t0001-h2
	sudo rm -rf /etc/netns/t0001-{h1,h2}
}
