#!/bin/bash
#
# Copyright (c) 2012 Tom Grennan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/ .

t0002_description="A bridged network."
read -d '' t0002_diagram <<-"EOF"
	\\th1 --- b1 --- h2
EOF

t0002_hosts="h1 b1 h2"
t0002_h1="10.100.0.1"
t0002_b1="10.100.0.11"
t0002_h2="10.100.0.2"
t0002_h1_lo="$t0002_h1/32"
t0002_b1_lo="$t0002_b1/32"
t0002_h2_lo="$t0002_h2/32"
t0002_nets="n1 n2"
t0002_n1_hosts="h1 b1"
t0002_n2_hosts="b1 h2"
t0002_b1_bridges="b1"
t0002_b1_b1_nets="n1 n2"
t0002_h1_n1="$t0002_h1 peer 10.100.0.0/28"
t0002_b1_b1="$t0002_b1 peer 10.100.0.0/28"
t0002_h2_n2="$t0002_h2 peer 10.100.0.0/28"

source ${0%/*}/netns

caption 'h1 ping b1' expect ok on h1 ping -A -c5 -w2 b1 >/dev/null
caption 'b1 ping h2' expect ok on b1 ping -A -c5 -w2 h2 >/dev/null
caption 'h1 ping h2' expect ok on h1 ping -A -c5 -w2 h2 >/dev/null
caption 'h2 ping b1' expect ok on h2 ping -A -c5 -w2 b1 >/dev/null
caption 'b1 ping h1' expect ok on b1 ping -A -c5 -w2 h1 >/dev/null
caption 'h2 ping h1' expect ok on h2 ping -A -c5 -w2 h1 >/dev/null
