#!/bin/bash
#
# Copyright (c) 2012 Tom Grennan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/ .

t0102_description="A bridged network with rip routing of host addresses."
read -d '' t0102_diagram <<-"EOF"
	\\th1 --- b1 --- h2
EOF

t0102_hosts="h1 h2 b1"
t0102_h1="10.100.0.1"
t0102_h2="10.100.0.2"
t0102_b1="10.100.0.11"
t0102_h1_lo="$t0102_h1/32"
t0102_h2_lo="$t0102_h2/32"
t0102_b1_lo="$t0102_b1/32"
t0102_nets="n1 n2"
t0102_n1_hosts="h1 b1"
t0102_n2_hosts="b1 h2"
t0102_b1_bridges="b1"
t0102_b1_b1_nets="n1 n2"
t0102_h1_n1="10.100.1.1/28 broadcast 10.100.1.15"
t0102_h2_n2="10.100.1.2/28 broadcast 10.100.1.15"
t0102_b1_b1="10.100.1.11/28 broadcast 10.100.1.15"

read -d '' t0102_h1_Quagga <<-EOF 
	router rip
	 network 10.100.1.0/28
	 network n1
	 route $t0102_h1/32
EOF

read -d '' t0102_h2_Quagga <<-EOF
	router rip
	 network 10.100.1.0/28
	 network n2
	 route $t0102_h2/32
EOF

read -d '' t0102_b1_Quagga <<-EOF
	router rip
	 network 10.100.1.0/28
	 network b1
	 route $t0102_b1/32
EOF

source ${0%/*}/netns

caption convergence retry 5 expect output="\'$t0102_h2 via*\'" \
	on h1 ip route list $t0102_h2
caption 'ping h2' expect ok on h1 ping -A -c 5 -w 2 h2 >/dev/null
caption 'ping h1' expect ok on h1 ping -A -c 5 -w 2 h1 >/dev/null
