#!/bin/bash
#
# Copyright (c) 2012 Tom Grennan
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/ .

test_description="No name spaces at all, just testing the harness."

source ${0%/*}/netns

example-message () {		# STYLE ....
	style=$1; shift
	say "$style" This is the first line of a $style message.
	say $style This is the secondline with \"double-quotes\".
	say $style This is the third line with \'single-quotes\'.
	say $style <<-EOF
		This is the fourth...
		fifth...
		and final line.
	EOF
}

for m in plain error skip pass info ; do
	caption "$m-message" expect ok example-message $m
done

caption "expect ok" expect ok true
caption "expect failure" expect failure false
caption "expect output match" expect output=foo echo -n foo

may say plain You will not see this unless --dry-run. >/dev/null
may tee /tmp/$prog-here-example <<-EOF >/dev/null
	This is a here document example.
EOF
caption compare expect ok cmp -b /tmp/$prog-here-example - <<-EOF
	This is a here document example.
EOF
may rm -f /tmp/$prog-here-example

caption pipeline expect ok say plain foo bar \| grep -q foo
